site_name: ENIGMA-PD docs
theme:
  name: material

features:
  - navigation.indexes

nav:
  - Welcome: index.md
  - Working Group:    
    - Core team: working_group/core_team.md
    - Sites: working_group/sites.md
    - Information for new sites: working_group/new_sites.md
    
  - Ongoing Projects: projects/overview.md

  - Completed Projects: 

  - Resources: resources/overview.md
    
  

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
