site_name: ENIGMA-PD docs
theme:
  name: material
  logo: docs/logos/enigma_300DPI_small.png
  favicon: docs/logos/enigma_300DPI_small.png
  palette:
    primary: teal
  

features:
  - navigation.indexes

nav:
  - Welcome: index.md
  - About ENIGMA-PD:    
    - Core team: working_group/core_team.md
    - Sites: working_group/sites.md
    - Information for new sites: working_group/new_sites.md
    
  - Ongoing Projects: 
    - Overview: projects/ongoing/overview.md
    - FreeSurfer 7: projects/ongoing/freesurfer7.md
    - Cognitive reserve: projects/ongoing/cognitive_reserve.md
    - White matter lesions: projects/ongoing/wml.md
    - Multiple Symptom Progression Modelling: projects/ongoing/mspm.md
    - Neuropsychiatry: projects/ongoing/neuropsych.md
    - Spinal Cord: projects/ongoing/spinal_cord.md
    - Imaging Genetics: projects/ongoing/imaging_genetics.md
    - Normative modelling (fMRI): projects/ongoing/normative_modelling.md

  - Completed Projects: 
    - Overview: projects/completed/overview.md
    - Cortical-Subcortical: projects/completed/cort_sub.md
    - Subcortical shape: projects/completed/shape.md
    - Diffusion (TBSS): projects/completed/tbss.md
    - PySustain: projects/completed/py-sustain.md
    - Connectomics: projects/completed/connectomics.md

  - Resources: 
    - Overview: resources/overview.md
    - ENIGMA-PD preregistrations: resources/preregistrations.md
    
  

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
